version: '3'

services:
  main_process:
    build:
      context: ../../
      dockerfile: ./shared/Dockerfile
    volumes:
      - ../../results/:/usr/src/app/results
    working_dir: /usr/src/app/ipc-methods/benchmark
    environment:
      - NODE_ENV=production
      - MOCK_DATA_SIZE
    command: 'node --max-old-space-size=1536 ./main.js'
