name: Run test suite

on:
  push:
    branches: [main, test/gh-actions-run-test-suite] # TODO: remove test branch!

jobs:
  run_test_suite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install top level dependencies
        run: |
          npm ci

      - name: Transpile the types package
        run: |
          cd types
          npm ci
          npm run tsc

      # - name: Run the test suite
      #   run: npm run full-test-suite

      - name: Create results index and publish
        run: |
          npm run tsc
          npm run index-results
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run publish-results -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
