name: Deploy UI

on:
  push:
    branches: [main, test/gh-actions-run-test-suite] # TODO: remove test branch!

jobs:
  run_test_suite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install top level dependencies
        run: npm ci

      - name: Transpile the types package
        run: |
          cd types
          npm ci
          npm run tsc

      - name: TESTING, run the test suite
        run: npm run full-test-suite

      - name: list and print result
        run: |
          ls -la results
          echo ""
          cat results/*

      - name: give a friendly reminder
        run: |
          echo "TODO: do something with the results"
